package passport.validation

import com.synechron.visaapplication.domain.Validation;
import com.synechron.visaapplication.domain.VisaApplication;
import com.synechron.visaapplication.domain.Visa;

rule "Report were visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 20
	when
        Visa()
	then
	  System.out.println("Conclusion: at least one visa was issued");
end

rule "Report no visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 10
	when
        VisaApplication( validation == Validation.FAILED )
	then
	  System.out.println("Conclusion: no visas were issued");
end
