package passport.validation

import com.synechron.visaapplication.domain.Passport;
import com.synechron.visaapplication.domain.Visa;
import com.synechron.visaapplication.domain.Visa;
import com.synechron.visaapplication.domain.VisaApplication;
import com.synechron.visaapplication.domain.ValidVisaApplication;
import com.synechron.visaapplication.domain.Validation;

rule "Issue Visa"
    when
        $visaApplication : VisaApplication()
        $passport : Passport(this.passportNumber == $visaApplication.passportNumber)
        not(InvalidPassport(this.passport == $passport))
        not(InvalidVisaApplication(this.visaApplication == $visaApplication))
    then
        Visa visa = new Visa($visaApplication.getPassportNumber());
        System.out.println ("Issue Visa : "+visa);
        insertLogical(visa);
end