package passport.validation

import com.synechron.visaapplication.domain.Passport;
import com.synechron.visaapplication.domain.Validation;
import com.synechron.visaapplication.domain.ValidPassport;
import com.synechron.visaapplication.domain.InvalidPassport;
import java.time.LocalDate;

rule "Expired Passport"
    when
         $passport :  Passport(isExpired() )
    then
        insert(new InvalidPassport($passport));
        System.out.println( $passport + "Expired Passport ");
end

rule "Full Passport"
    when
         $passport :  Passport(unusedVisaPages == 0)
    then
         insert(new InvalidPassport($passport));
        System.out.println($passport + "Full Passport");
end



