package passport.validation

import com.synechron.visaapplication.domain.Passport;
import com.synechron.visaapplication.domain.ValidPassport;
import com.synechron.visaapplication.domain.InvalidPassport;
import com.synechron.visaapplication.domain.Validation;
import com.synechron.visaapplication.domain.VisaApplication;
import com.synechron.visaapplication.domain.InvalidVisaApplication;
import com.synechron.visaapplication.domain.ValidVisaApplication;
import java.time.LocalDate;

rule "Marking failed all the visa applicaiton whose passport expiry date in not active after the trip end date + 6 month"
    when
      $passport: Passport()
    	  not( InvalidPassport( this.passport == $passport) )
          $visaApplication : VisaApplication(passportNumber == $passport.passportNumber, $passport.expiresOn.isBefore(visitEndDate.plusMonths(6)))
    then
            insert(new InvalidVisaApplication($visaApplication));
            System.out.println("Invalid Visa Application : " + $visaApplication+". Passport is not active after the 6 moth of the trip end date");

end








