import com.synechron.visaapplication.modal.TaxiRide;
import com.synechron.visaapplication.modal.Fare;
import java.util.*;

global com.synechron.visaapplication.modal.Fare rideFare;
dialect  "mvel"

rule "Calculate Taxi Fare - Scenario 1"
    when
        taxiRideInstance:TaxiRide(nightSurcharge == false && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(0);
       	rideFare.setRideFare(70);
end

